### ISSUE TITLE
Session Handling

### ISSUE THREAD

**Issue by bbergen** [bbergen/tbmd.com#18]
Once #1, #9, #8 and #7 are done, we need to add session handling for tracking when the user is logged in or out of the site, and what actions they can take in either state.

This is just a stub for now.

**Comment by ecs0** [comment]
After session handling is completed, we should generate content based on the current session of the user, such as updating views based on pages that have been visited during that session, and potentially store that information for future visits, thus ensuring a unique and dynamic experience for every user.

**Comment by bbergen** [comment]
This has basically been taken care of in #1 outside of any advanced functionality. If we do come up with addition session based features, we can make a new issue for it. 

Closing this one for now.
