### ISSUE TITLE
Generate Content

### ISSUE THREAD

**Issue by bbergen** [bbergen/tbmd.com#21]
When it comes time to present, we want out website to have a ton of real quality content on it, stuff like real movies, with real images of people and movie posters. 

Acceptance Criteria:

* At least 12 movies in the database with full images, more is better
* 20 or so actors and directors, more is better
* At least 2-3 reviews per movie

A lot of this content can just be ripped right from Wikipedia or something similar, don't worry about making it original.

**Comment by bbergen** [comment]
#20 should be done before this issue as it will make it much easier to pass around the images/database

**Comment by bbergen** [comment]
There are currently 33 people and 15 movies in the production database. 

@ecs0 Feel free to start adding reviews and backing them up to the production database. Make sure everything is clean before you do so (best to delete all the images in images/uploads before you run manage -r)

**Comment by ecs0** [comment]
I'll start adding shortly. I'm getting closer to something acceptable for
the RSS system.

**Comment by bbergen** [comment]
@ecs0 

Project has about 25MB of database in it (obviously mostly images), so its probably best if we just stick to adding reviews from now on. Maybe more users as well (and reviews from them). 

Also, its important due to a quick in the database call (and laziness on my part to avoid fixing it) we should refrain from making any reviews on Tuesday so that reviews made during the presentation show up at the top of the front page (they sort by date but not time).

**Comment by bbergen** [comment]
I think we are probably good on content for the final submission.
