### ISSUE TITLE
Movie Ratings

### ISSUE THREAD

**Issue by bbergen** [bbergen/tbmd.com#34]
Movie Ratings are currently out of 5.
They are also visually bland

* Update the forms to allow movies to be rated 1-10
* Style the rating spinner on the review form to be a series of stars to mouse over to fill
* Present the rating in reviews as a row of filled/unfilled stars

**Comment by bbergen** [comment]
[Relevant jQuery Tutorial](http://code.tutsplus.com/tutorials/building-a-5-star-rating-system-with-jquery-ajax-and-php--net-11541)

**Comment by bbergen** [comment]
@ecs0 I made some changes to the structure of the review form. If you've already begun there may be merge conflicts, if you haven't, be sure to pull before you begin.

**Comment by ecs0** [comment]
@bbergen Thanks for the heads up.
