### ISSUE TITLE
RSS Automation

### ISSUE THREAD

**Issue by ecs0** [bbergen/tbmd.com#45]
As a developer, I would like the RSS feed to be updated automatically when new movies, actors and directors are created.

Acceptance Criteria

* RSS feed updated when new entries are added to the site.

**Comment by bbergen** [comment]
@ecs0 Should the rss link on index.php be a relative link rather than a hard coded link to the tmbd.com domain? Clicking it takes me to the actual tbmd.com on my computer.

Shouldn't the link be something like `href="/script/rss.xml"`?

**Comment by ecs0** [comment]
Absolutely correct. My bad.

**Comment by bbergen** [comment]
@ecs0 I think that perhaps the rss.xml should be added the to .gitignore file Tim. Currently any additions to the database results in a changes that would be commit.

Local database changes should have zero impact on the state of the repo unless the manage tool is used to backup the production database. 

This is would be a huge source of merge conflicts moving forward.
