### ISSUE TITLE
SQL Injection Vulnerabilities

### ISSUE THREAD

**Issue by FrancisBaileyH** [bbergen/tbmd.com#48]
Hey Bryan hope you don't mind, I was just perusing your source code. I just thought I'd give you a heads up that your mysql_* calls are vulnerable to sql injections. I'd consider using prepared statements via mysqli or the pdo library.

**Comment by bbergen** [comment]
Hey Francis, thanks for the input. I totally agree. Thankfully this project will likely never be in a production environment. It was just the final project for COSC 213. Such a shame that they teach sub par programming in some of our courses. (mysqli is what was taught to us). 

Cheers!

**Comment by FrancisBaileyH** [comment]
Oh makes total sense, I was under the impression it was a live site or something, so just thought I'd give a heads up. Yeah agreed.
