### ISSUE TITLE
Base page structure for reviews

### ISSUE THREAD

**Issue by ecs0** [bbergen/tbmd.com#8]
As a user I want to view all the information for a particular review.

* Dynamically display all the content without writing logic for a specific page.

**Comment by bbergen** [comment]
I'm not entirely sure we need a full distinct page for a review. Might want to play this one by ear. Right now reviews are listed below a movie on the movie page, so any review can be found simply by search for the appropriate movie.

**Comment by bbergen** [comment]
Closing this for now as I don't see us needing it.
